---
Description: Cloudwatch - Log Group for VPC Logs

Parameters:
  LogGroupName:
    Type: String
    Description: The name of the log group for the ec2 instances
  RetentionInDays:
    Type: String
    Default: "7"
    AllowedPattern: "(1|3|5|7|14|30|60|90|120|150|180|365|400|545|731|1827|3653)"

Resources:
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Ref LogGroupName
      RetentionInDays: !Ref RetentionInDays

Outputs:
  LogGroupName:
    Value: !Ref LogGroup
    Export:
      Name: !Sub "${AWS::StackName}::LogGroupName"

  LogGroupArn:
    Value: !GetAtt LogGroup.Arn
    Export:
      Name: !Sub "${AWS::StackName}::LogGroupArn"
