Description: S3 - Bucket 
Parameters:
  OrganisationalId:
    Type: String
  Environment:
    Type: String
  BucketName:
    Type: String
  
Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: !Sub "${OrganisationalId}-${Environment}-${BucketName}"

Outputs:
  Bucket:
    Value: !Ref Bucket 
    Export:
      Name: !Sub "${AWS::StackName}::Bucket"
  BucketArn:
    Value: !GetAtt Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}::BucketArn"